### ISSUE TITLE
Run ninja error when using ubuntu 18.04 

### ISSUE THREAD

**Issue by FalFlower** [facebookresearch/vrs#89]
Hello,I'm trying to get this VRS library to build with ubuntu 18.04.

The cmake compilation part is fine. However, while executing the `ninja all` command, the following two problems occurred:
1.Appeared in jDocumentToJsonStringPretty function template instantiation of compile errors.

error log:
`
/usr/include/cereal/external/rapidjson/prettywriter.h:199:25: error: ‘fb_rapidjson::GenericStringBuffer[fb_rapidjson::UTF8&lt;](fb_rapidjson::UTF8%3C) >* fb_rapidjson::Writer[fb_rapidjson::GenericStringBufferfb_rapidjson::utf8&lt;&lt; &gt; &gt;::os_’ is protected within this context](fb_rapidjson::GenericStringBuffer%3Cfb_rapidjson::UTF8%3C)
`
I solved this part of the problem by referring to the method given by mBORowS2 in the last issue.

2.An error of “fatal error: vrs/os/CompilerAttributes.h: No such file or directory” has occurred.

error log:

I made sure all the required libraries were installed, such as LZ4, ZSTD, etc.

full log:

```
[2/85] Building CXX object vrs/oss/log...MakeFiles/vrs_logging.dir/Checks.cpp.o
FAILED: vrs/oss/logging/CMakeFiles/vrs_logging.dir/Checks.cpp.o 
/usr/bin/ccache /usr/bin/c++  -I"/home/patrick/ffsnow_zhang/vrs/VRS_Code/vrs/oss/logging/'~/ffsnow_zhang/vrs/VRS_Code'" -O3 -DNDEBUG -fPIC -std=c++1z -MD -MT vrs/oss/logging/CMakeFiles/vrs_logging.dir/Checks.cpp.o -MF vrs/oss/logging/CMakeFiles/vrs_logging.dir/Checks.cpp.o.d -o vrs/oss/logging/CMakeFiles/vrs_logging.dir/Checks.cpp.o -c /home/patrick/ffsnow_zhang/vrs/VRS_Code/vrs/oss/logging/Checks.cpp
In file included from /home/patrick/ffsnow_zhang/vrs/VRS_Code/vrs/oss/logging/Checks.cpp:17:0:
/home/patrick/ffsnow_zhang/vrs/VRS_Code/vrs/oss/logging/Checks.h:23:10: fatal error: vrs/os/CompilerAttributes.h: No such file or directory
 #include <vrs/os/CompilerAttributes.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[3/85] Building CXX object vrs/utils/C...rs_utils.dir/test/PixelFrameTest.cpp.o
FAILED: vrs/utils/CMakeFiles/test_vrs_utils.dir/test/PixelFrameTest.cpp.o 
/usr/bin/ccache /usr/bin/c++ -DOSS_BUILD_MODE -I/home/patrick/ffsnow_zhang/vrs/VRS_Code -I/home/patrick/ffsnow_zhang/vrs/VRS_Code/vrs/oss -O3 -DNDEBUG -fPIE -std=c++1z -MD -MT vrs/utils/CMakeFiles/test_vrs_utils.dir/test/PixelFrameTest.cpp.o -MF vrs/utils/CMakeFiles/test_vrs_utils.dir/test/PixelFrameTest.cpp.o.d -o vrs/utils/CMakeFiles/test_vrs_utils.dir/test/PixelFrameTest.cpp.o -c /home/patrick/ffsnow_zhang/vrs/VRS_Code/vrs/utils/test/PixelFrameTest.cpp
ccache: error: Failed to create temporary file for /home/patrick/.ccache/6/d/3af26ea0fbd669c82720343da0570b-2835.manifest.tmp: Permission denied
[4/85] Building CXX object vrs/CMakeFiles/vrslib.dir/Decompressor.cpp.o
FAILED: vrs/CMakeFiles/vrslib.dir/Decompressor.cpp.o 
/usr/bin/ccache /usr/bin/c++ -DCEREAL_RAPIDJSON_NAMESPACE=fb_rapidjson -DCEREAL_RAPIDJSON_PARSE_DEFAULT_FLAGS="kParseFullPrecisionFlag|kParseNanAndInfFlag" -DCEREAL_RAPIDJSON_WRITE_DEFAULT_FLAGS=kWriteNoFlags -DCEREAL_THREAD_SAFE=1 -DOSS_BUILD_MODE -I/home/patrick/ffsnow_zhang/vrs/VRS_Code -I/home/patrick/ffsnow_zhang/vrs/VRS_Code/vrs/oss -O3 -DNDEBUG -fPIC -std=c++1z -MD -MT vrs/CMakeFiles/vrslib.dir/Decompressor.cpp.o -MF vrs/CMakeFiles/vrslib.dir/Decompressor.cpp.o.d -o vrs/CMakeFiles/vrslib.dir/Decompressor.cpp.o -c /home/patrick/ffsnow_zhang/vrs/VRS_Code/vrs/Decompressor.cpp
/home/patrick/ffsnow_zhang/vrs/VRS_Code/vrs/Decompressor.cpp: In member function ‘void vrs::Decompressor::Lz4Decompressor::resetContext()’:
/home/patrick/ffsnow_zhang/vrs/VRS_Code/vrs/Decompressor.cpp:57:5: error: ‘LZ4F_resetDecompressionContext’ was not declared in this scope
     LZ4F_resetDecompressionContext(context_);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/patrick/ffsnow_zhang/vrs/VRS_Code/vrs/Decompressor.cpp:57:5: note: suggested alternative: ‘LZ4F_freeDecompressionContext’
     LZ4F_resetDecompressionContext(context_);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     LZ4F_freeDecompressionContext
[5/85] Building CXX object vrs/CMakeFiles/vrslib.dir/Compressor.cpp.o
FAILED: vrs/CMakeFiles/vrslib.dir/Compressor.cpp.o 
/usr/bin/ccache /usr/bin/c++ -DCEREAL_RAPIDJSON_NAMESPACE=fb_rapidjson -DCEREAL_RAPIDJSON_PARSE_DEFAULT_FLAGS="kParseFullPrecisionFlag|kParseNanAndInfFlag" -DCEREAL_RAPIDJSON_WRITE_DEFAULT_FLAGS=kWriteNoFlags -DCEREAL_THREAD_SAFE=1 -DOSS_BUILD_MODE -I/home/patrick/ffsnow_zhang/vrs/VRS_Code -I/home/patrick/ffsnow_zhang/vrs/VRS_Code/vrs/oss -O3 -DNDEBUG -fPIC -std=c++1z -MD -MT vrs/CMakeFiles/vrslib.dir/Compressor.cpp.o -MF vrs/CMakeFiles/vrslib.dir/Compressor.cpp.o.d -o vrs/CMakeFiles/vrslib.dir/Compressor.cpp.o -c /home/patrick/ffsnow_zhang/vrs/VRS_Code/vrs/Compressor.cpp
/home/patrick/ffsnow_zhang/vrs/VRS_Code/vrs/Compressor.cpp: In member function ‘int vrs::Compressor::CompressorImpl::startFrame(size_t, vrs::CompressionPreset)’:
/home/patrick/ffsnow_zhang/vrs/VRS_Code/vrs/Compressor.cpp:178:9: error: ‘ZSTD_CCtx_setParameter’ was not declared in this scope
         ZSTD_CCtx_setParameter(zstdContext_, compressionLevel, compressionLevel));
         ^
/home/patrick/ffsnow_zhang/vrs/VRS_Code/vrs/Compressor.cpp:97:15: note: in definition of macro ‘IF_ZCOMP_ERROR_LOG_AND_RETURN’
     zresult = operation__;                                                               \
               ^~~~~~~~~~~
/home/patrick/ffsnow_zhang/vrs/VRS_Code/vrs/Compressor.cpp:178:9: note: suggested alternative: ‘ZSTD_CCtx_s’
         ZSTD_CCtx_setParameter(zstdContext_, compressionLevel, compressionLevel));
         ^
/home/patrick/ffsnow_zhang/vrs/VRS_Code/vrs/Compressor.cpp:97:15: note: in definition of macro ‘IF_ZCOMP_ERROR_LOG_AND_RETURN’
     zresult = operation__;                                                               \
               ^~~~~~~~~~~
/home/patrick/ffsnow_zhang/vrs/VRS_Code/vrs/Compressor.cpp:180:35: error: ‘ZSTD_CCtx_setPledgedSrcSize’ was not declared in this scope
     IF_ZCOMP_ERROR_LOG_AND_RETURN(ZSTD_CCtx_setPledgedSrcSize(zstdContext_, dataSize));
                                   ^
/home/patrick/ffsnow_zhang/vrs/VRS_Code/vrs/Compressor.cpp:97:15: note: in definition of macro ‘IF_ZCOMP_ERROR_LOG_AND_RETURN’
     zresult = operation__;                                                               \
               ^~~~~~~~~~~
/home/patrick/ffsnow_zhang/vrs/VRS_Code/vrs/Compressor.cpp: In member function ‘int vrs::Compressor::CompressorImpl::addFrameData(vrs::WriteFileHandler&, ZSTD_inBuffer_s*, ZSTD_outBuffer_s*, uint32_t&, size_t, bool)’:
/home/patrick/ffsnow_zhang/vrs/VRS_Code/vrs/Compressor.cpp:195:62: error: expected primary-expression before ‘:’ token
           zstdContext_, output, input, endFrame ? ZSTD_DDict : ZSTD_e_continue));
                                                              ^
/home/patrick/ffsnow_zhang/vrs/VRS_Code/vrs/Compressor.cpp:97:15: note: in definition of macro ‘IF_ZCOMP_ERROR_LOG_AND_RETURN’
     zresult = operation__;                                                               \
               ^~~~~~~~~~~
/home/patrick/ffsnow_zhang/vrs/VRS_Code/vrs/Compressor.cpp:195:64: error: ‘ZSTD_e_continue’ was not declared in this scope
           zstdContext_, output, input, endFrame ? ZSTD_DDict : ZSTD_e_continue));
                                                                ^
/home/patrick/ffsnow_zhang/vrs/VRS_Code/vrs/Compressor.cpp:97:15: note: in definition of macro ‘IF_ZCOMP_ERROR_LOG_AND_RETURN’
     zresult = operation__;                                                               \
               ^~~~~~~~~~~
/home/patrick/ffsnow_zhang/vrs/VRS_Code/vrs/Compressor.cpp:199:41: error: ‘ZSTD_reset_session_only’ was not declared in this scope
           ZSTD_CCtx_reset(zstdContext_, ZSTD_reset_session_only);
                                         ^~~~~~~~~~~~~~~~~~~~~~~
/home/patrick/ffsnow_zhang/vrs/VRS_Code/vrs/Compressor.cpp:199:11: error: ‘ZSTD_CCtx_reset’ was not declared in this scope
           ZSTD_CCtx_reset(zstdContext_, ZSTD_reset_session_only);
           ^~~~~~~~~~~~~~~
/home/patrick/ffsnow_zhang/vrs/VRS_Code/vrs/Compressor.cpp:199:11: note: suggested alternative: ‘ZSTD_CCtx_s’
           ZSTD_CCtx_reset(zstdContext_, ZSTD_reset_session_only);
           ^~~~~~~~~~~~~~~
           ZSTD_CCtx_s
[10/85] Building CXX object vrs/test/C...r/file_tests/DeviceSimulatorTest.cpp.o
FAILED: vrs/test/CMakeFiles/test_vrslib_file_tests.dir/file_tests/DeviceSimulatorTest.cpp.o 
/usr/bin/ccache /usr/bin/c++ -DCEREAL_RAPIDJSON_NAMESPACE=fb_rapidjson -DCEREAL_RAPIDJSON_PARSE_DEFAULT_FLAGS="kParseFullPrecisionFlag|kParseNanAndInfFlag" -DCEREAL_RAPIDJSON_WRITE_DEFAULT_FLAGS=kWriteNoFlags -DCEREAL_THREAD_SAFE=1 -DGTEST_BUILD -DOSS_BUILD_MODE -I/home/patrick/ffsnow_zhang/vrs/VRS_Code -I/home/patrick/ffsnow_zhang/vrs/VRS_Code/vrs/oss -O3 -DNDEBUG -fPIE -std=c++1z -MD -MT vrs/test/CMakeFiles/test_vrslib_file_tests.dir/file_tests/DeviceSimulatorTest.cpp.o -MF vrs/test/CMakeFiles/test_vrslib_file_tests.dir/file_tests/DeviceSimulatorTest.cpp.o.d -o vrs/test/CMakeFiles/test_vrslib_file_tests.dir/file_tests/DeviceSimulatorTest.cpp.o -c /home/patrick/ffsnow_zhang/vrs/VRS_Code/vrs/test/file_tests/DeviceSimulatorTest.cpp
ccache: error: Failed to create temporary file for /home/patrick/.ccache/2/9/dff9a6c676ac569d76c4b5f36999bb-3804549.o.tmp.stdout: Permission denied
[11/85] Building CXX object vrs/test/C..._helpers.dir/helpers/TestProcess.cpp.o
FAILED: vrs/test/CMakeFiles/vrs_test_helpers.dir/helpers/TestProcess.cpp.o 
/usr/bin/ccache /usr/bin/c++ -DCEREAL_RAPIDJSON_NAMESPACE=fb_rapidjson -DCEREAL_RAPIDJSON_PARSE_DEFAULT_FLAGS="kParseFullPrecisionFlag|kParseNanAndInfFlag" -DCEREAL_RAPIDJSON_WRITE_DEFAULT_FLAGS=kWriteNoFlags -DCEREAL_THREAD_SAFE=1 -DGTEST_BUILD -DOSS_BUILD_MODE -I/home/patrick/ffsnow_zhang/vrs/VRS_Code -I/home/patrick/ffsnow_zhang/vrs/VRS_Code/vrs/oss -O3 -DNDEBUG -fPIC -std=c++1z -MD -MT vrs/test/CMakeFiles/vrs_test_helpers.dir/helpers/TestProcess.cpp.o -MF vrs/test/CMakeFiles/vrs_test_helpers.dir/helpers/TestProcess.cpp.o.d -o vrs/test/CMakeFiles/vrs_test_helpers.dir/helpers/TestProcess.cpp.o -c /home/patrick/ffsnow_zhang/vrs/VRS_Code/vrs/test/helpers/TestProcess.cpp
ccache: error: Failed to create temporary file for /home/patrick/.ccache/2/9/a560c75fee96c5a57956dbff8466da-3765.manifest.tmp: Permission denied
ninja: build stopped: subcommand failed.
```

Any help would be greatly appreciated T_T

**Comment by georges-berenger** [comment]
18.04 is now 2 LTS releases old. I'm not sure about the 2 first issues, which look like some library setup issue, but the later tells me you also got an outdated version of zstd.  The `vrs/os/CompilerAttributes.h` not found issue is odd, because this header is part of vrs, and that tells me cmake just isn't seeing the vrs source tree correctly for some obscure reason. If such a file, part of the distribution can be found, something's really off with your setup.
I can only recommend you use 20.4 or later, sorry...
